WORLD_CUP_2026_PARTICIPANTS = [
    "Mexico",
    "South Africa",
    "South Korea",
    "Czech Republic",
    "Canada",
    "Bosnia and Herzegovina",
    "Qatar",
    "Switzerland",
    "Brazil",
    "Morocco",
    "Haiti",
    "Scotland",
    "United States",
    "Paraguay",
    "Australia",
    "Turkey",
    "Germany",
    "Curaçao",
    "Ivory Coast",
    "Ecuador",
    "Netherlands",
    "Japan",
    "Sweden",
    "Tunisia",
    "Belgium",
    "Egypt",
    "Iran",
    "New Zealand",
    "Spain",
    "Cape Verde",
    "Saudi Arabia",
    "Uruguay",
    "France",
    "Senegal",
    "Iraq",
    "Norway",
    "Argentina",
    "Algeria",
    "Austria",
    "Jordan",
    "Portugal",
    "DR Congo",
    "Uzbekistan",
    "Colombia",
    "England",
    "Croatia",
    "Ghana",
    "Panama",
]

WORLD_CUP_2026_PARTICIPANT_SET = {team.casefold() for team in WORLD_CUP_2026_PARTICIPANTS}


def is_world_cup_2026_participant(team_name: str) -> bool:
    return team_name.strip().casefold() in WORLD_CUP_2026_PARTICIPANT_SET
